version: '3'

networks:
  monitor-net:
    driver: overlay
  rp:
    external:
      name: rp

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    networks:
      - monitor-net
  
  alertmanager:
    image: prom/alertmanager
    volumes: 
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    networks:
      - monitor-net

  nodeexporter:
    image: prom/node-exporter
    restart: unless-stopped
    networks:
      - monitor-net

  cadvisor:
    image: google/cadvisor:v0.24.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - monitor-net
  
  grafana:
    image: grafana/grafana
    environment:
    - VIRTUAL_HOST=grafana.3r1.co
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - user.config
    restart: unless-stopped
    networks:
      - monitor-net
      - rp
